name: Rakuten Protein Ranking Bot

on:
  schedule:
    - cron: '0 12 * * *'  # 毎日12:00 (JST: 21:00) に実行
  workflow_dispatch:  # 手動実行も可能

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Python セットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 依存関係をインストール
        run: pip install requests pandas numpy tweepy

      - name: 環境変数を設定
        env:
          RAKUTEN_APP_ID: ${{ secrets.APP_ID }}
          RAKUTEN_AFFILIATE_ID: ${{ secrets.AFFILIATEID }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: python main.py

      - name: CSVファイルをアーティファクトとして保存
        uses: actions/upload-artifact@v4
        with:
          name: rakuten_protein_data
          path: ./rakuten_protein_data.csv
          retention-days: 7
